[package]
name = "todo_api"
version = "0.1.0"
edition = "2024"
default-run = "todo_api"

[features]
default = ["sqlite"]
sqlite = []

[dependencies]
axum = "0.8"
che-rest = { path = "../../che-rest" }
che-orm2 = { path = "../../che-orm2" }
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["macros", "net", "rt-multi-thread", "sync"] }
