use std::{fs, path::Path};

use crate::module::ApiEndpoint;

const HEADER: &str = "// This file is generated by che-rest. Do not edit manually.\n// Run the appropriate che-rest management generator to update it.\n\n";

pub fn generate(
    out: &Path,
    endpoints: &[ApiEndpoint],
    force: bool,
) -> Result<Vec<String>, std::io::Error> {
    let admin_generated = out.join("src/admin/generated");
    let admin_dir = out.join("src/admin");
    fs::create_dir_all(&admin_generated)?;
    fs::create_dir_all(&admin_dir)?;
    let schema_path = admin_generated.join("adminSchema.ts");
    let routes_path = admin_generated.join("adminRoutes.ts");
    fs::write(&schema_path, admin_schema(endpoints))?;
    fs::write(&routes_path, admin_routes(endpoints))?;
    fs::write(
        admin_dir.join("adminSchema.ts"),
        format!("{HEADER}export * from \"./generated/adminSchema\";\n"),
    )?;
    for (relative, contents) in static_files(endpoints) {
        let path = out.join(relative);
        if force || !path.exists() {
            if let Some(parent) = path.parent() {
                fs::create_dir_all(parent)?;
            }
            fs::write(path, contents)?;
        }
    }
    Ok(vec![
        "src/admin/generated/adminSchema.ts".into(),
        "src/admin/generated/adminRoutes.ts".into(),
        "src/admin/adminSchema.ts".into(),
    ])
}

fn admin_schema(endpoints: &[ApiEndpoint]) -> String {
    let mut out = HEADER.to_owned();
    out.push_str("import {\n");
    let mut apps = Vec::new();
    for endpoint in endpoints {
        out.push_str(&format!("  {}Api,\n", api_name(endpoint, endpoints)));
    }
    out.push_str("} from \"../../generated/api\";\n\n");
    out.push_str("export type AdminFieldType = \"integer\" | \"text\" | \"boolean\" | \"real\" | \"datetime\";\n\n");
    out.push_str(
        "export interface AdminField { name: string; source: string; type: AdminFieldType; label: string; readOnly: boolean; writeOnly: boolean; required: boolean; nullable: boolean; hasDefault: boolean; choices?: string[]; relatedModel?: string; relationField?: string; }\n\nexport interface AdminFilter { name: string; source: string; type: AdminFieldType; label: string; nullable: boolean; choices?: string[]; }\n\nexport interface AdminModelApi { list: (params?: any) => Promise<{ count: number; results: any[] }>; retrieve: (id: number) => Promise<any>; create: (payload: any) => Promise<any>; update: (id: number, payload: any) => Promise<any>; remove: (id: number) => Promise<void>; }\n\nexport interface AdminModel { appName: string; name: string; resource: string; api: AdminModelApi; fields: AdminField[]; filters: AdminFilter[]; }\nexport interface AdminApp { name: string; models: AdminModel[]; }\n\nexport const adminModels: AdminModel[] = [\n",
    );
    for endpoint in endpoints {
        out.push_str("  {\n");
        out.push_str(&format!(
            "    appName: {}, name: {}, resource: {}, api: {}Api,\n",
            js(endpoint.app_name),
            js(&endpoint.model_name),
            js(&endpoint.resource),
            api_name(endpoint, endpoints)
        ));
        out.push_str("    fields: [\n");
        for field in &endpoint.fields {
            let related = field.related_model.map(last_path_part);
            let source = field.source.to_owned();
            let ty = admin_type(field.rust_type, related.is_some());
            let nested_relation = related.is_some_and(|_| field.name != field.source);
            let read_only = field.read_only || nested_relation;
            let column = endpoint.columns.iter().find(|column| column.name == source);
            let nullable = column.is_some_and(|column| column.nullable);
            let has_default = column.is_some_and(|column| column.has_default);
            let choices = column
                .and_then(|column| column.choices.as_ref())
                .map(|choices| format!(", choices: {}", serde_json::to_string(choices).unwrap()))
                .unwrap_or_default();
            let related_model = related
                .map(|value| format!(", relatedModel: {}", js(value)))
                .unwrap_or_default();
            let relation_field = if nested_relation {
                format!(", relationField: {}", js(field.name))
            } else {
                String::new()
            };
            out.push_str(&format!("      {{ name: {}, source: {}, type: {}, label: {}, readOnly: {}, writeOnly: {}, required: {}, nullable: {}, hasDefault: {}{}{}{} }},\n", js(field.name), js(&source), js(ty), js(&label(field.name)), read_only, field.write_only, !read_only && !field.write_only && !nullable && !has_default, nullable, has_default, choices, related_model, relation_field));
        }
        out.push_str("    ],\n    filters: [\n");
        for filter in &endpoint.filters {
            let suffix = match filter.lookup {
                crate::Lookup::Exact => "",
                crate::Lookup::Contains => "__contains",
                crate::Lookup::Gt => "__gt",
                crate::Lookup::Gte => "__gte",
                crate::Lookup::Lt => "__lt",
                crate::Lookup::Lte => "__lte",
            };
            let name = format!("{}{}", filter.name, suffix);
            let choices = endpoint
                .columns
                .iter()
                .find(|column| column.name == filter.source)
                .and_then(|column| column.choices.as_ref())
                .map(|choices| format!(", choices: {}", serde_json::to_string(choices).unwrap()))
                .unwrap_or_default();
            out.push_str(&format!(
                "      {{ name: {}, source: {}, type: {}, label: {}, nullable: false{} }},\n",
                js(&name),
                js(filter.source),
                js(filter_type(filter.source)),
                js(&label(&name)),
                choices
            ));
        }
        out.push_str("    ],\n  },\n");
    }
    out.push_str("];\n\n");
    for endpoint in endpoints {
        out.push_str(&format!("export const {}AdminModel = adminModels.find((model) => model.appName === {} && model.resource === {}) as AdminModel;\n", api_name(endpoint, endpoints), js(endpoint.app_name), js(&endpoint.resource)));
    }
    out.push_str("\nexport const adminApps: AdminApp[] = [\n");
    for endpoint in endpoints {
        if apps.contains(&endpoint.app_name) {
            continue;
        }
        apps.push(endpoint.app_name);
        out.push_str(&format!(
            "  {{ name: {}, models: adminModels.filter((model) => model.appName === {}) }},\n",
            js(endpoint.app_name),
            js(endpoint.app_name)
        ));
    }
    out.push_str("];\n");
    out
}

fn static_files(endpoints: &[ApiEndpoint]) -> Vec<(String, String)> {
    let mut files = vec![
        ("package.json".into(), r#"{"name":"che-rest-admin","private":true,"version":"0.1.0","type":"module","scripts":{"build":"vue-tsc --noEmit && vite build","dev":"vite"},"dependencies":{"@vitejs/plugin-vue":"^5.2.1","axios":"^1.7.9","typescript":"^5.7.2","vite":"^6.0.3","vue":"^3.5.13","vue-router":"^4.5.0","vue-tsc":"^2.1.10"}}"#.into()),
        ("index.html".into(), "<!doctype html><html><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>che-rest admin</title></head><body><div id=\"app\"></div><script type=\"module\" src=\"/src/main.ts\"></script></body></html>".into()),
        ("vite.config.ts".into(), "import vue from \"@vitejs/plugin-vue\";\nimport { defineConfig } from \"vite\";\nexport default defineConfig({ plugins: [vue()] });\n".into()),
        ("tsconfig.json".into(), r#"{"compilerOptions":{"target":"ES2020","useDefineForClassFields":true,"module":"ESNext","lib":["ES2020","DOM","DOM.Iterable"],"skipLibCheck":true,"moduleResolution":"Bundler","allowImportingTsExtensions":true,"resolveJsonModule":true,"isolatedModules":true,"noEmit":true,"jsx":"preserve","strict":true,"types":["vite/client"]},"include":["src/**/*.ts","src/**/*.vue"]}"#.into()),
        ("src/main.ts".into(), "import { createApp } from \"vue\";\nimport App from \"./App.vue\";\nimport router from \"./router\";\ncreateApp(App).use(router).mount(\"#app\");\n".into()),
        ("src/App.vue".into(), "<script setup lang=\"ts\">\nimport { RouterView } from \"vue-router\";\n</script>\n<template><RouterView /></template>\n".into()),
        ("src/router.ts".into(), "import { createRouter, createWebHistory } from \"vue-router\";\nimport { adminRoutes } from \"./admin/generated/adminRoutes\";\nexport default createRouter({ history: createWebHistory(), routes: adminRoutes });\n".to_string()),
        ("src/admin/AdminModelList.vue".into(), "<template><main><h1>Models</h1><RouterLink v-for=\"model in adminModels\" :key=\"model.resource\" :to=\"`/${model.resource}`\">{{ model.name }}</RouterLink></main></template>\n<script setup lang=\"ts\">\nimport { adminModels } from \"./generated/adminSchema\";\n</script>\n".into()),
        ("src/admin/components/GenericModelTable.vue".into(), "<script setup lang=\"ts\">\nimport { onMounted, ref } from \"vue\";\nconst props = defineProps<{ model: any }>(); const rows = ref<any[]>([]);\nonMounted(async () => { rows.value = (await props.model.api.list({ limit: 50 })).results; });\n</script>\n<template><main><h1>{{ model.name }}</h1><table><tr v-for=\"row in rows\" :key=\"row.id\"><td v-for=\"field in model.fields.filter((item: any) => !item.writeOnly)\" :key=\"field.name\">{{ row[field.name] }}</td></tr></table></main></template>\n".into()),
        ("src/admin/components/GenericModelForm.vue".into(), "<script setup lang=\"ts\">\nconst props = defineProps<{ model: any }>();\n</script>\n<template><main><h1>{{ model.name }}</h1><p>Use the generated API to edit this model.</p></main></template>\n".into()),
    ];
    files.clear();
    files.extend([
        (
            "package.json".into(),
            include_str!(concat!(
                env!("CARGO_MANIFEST_DIR"),
                "/src/admin/templates/package.json"
            ))
            .into(),
        ),
        (
            "index.html".into(),
            include_str!(concat!(
                env!("CARGO_MANIFEST_DIR"),
                "/src/admin/templates/index.html"
            ))
            .into(),
        ),
        (
            "vite.config.ts".into(),
            include_str!(concat!(
                env!("CARGO_MANIFEST_DIR"),
                "/src/admin/templates/vite.config.ts"
            ))
            .into(),
        ),
        (
            "tsconfig.json".into(),
            include_str!(concat!(
                env!("CARGO_MANIFEST_DIR"),
                "/src/admin/templates/tsconfig.json"
            ))
            .into(),
        ),
        (
            "src/main.ts".into(),
            include_str!(concat!(
                env!("CARGO_MANIFEST_DIR"),
                "/src/admin/templates/main.ts"
            ))
            .into(),
        ),
        (
            "src/App.vue".into(),
            include_str!(concat!(
                env!("CARGO_MANIFEST_DIR"),
                "/src/admin/templates/App.vue"
            ))
            .into(),
        ),
        (
            "src/router.ts".into(),
            include_str!(concat!(
                env!("CARGO_MANIFEST_DIR"),
                "/src/admin/templates/router.ts"
            ))
            .into(),
        ),
        (
            "src/admin/AdminApp.vue".into(),
            include_str!(concat!(
                env!("CARGO_MANIFEST_DIR"),
                "/src/admin/templates/AdminApp.vue"
            ))
            .into(),
        ),
        (
            "src/admin/AdminLogin.vue".into(),
            include_str!(concat!(
                env!("CARGO_MANIFEST_DIR"),
                "/src/admin/templates/AdminLogin.vue"
            ))
            .into(),
        ),
        (
            "src/admin/AdminModelList.vue".into(),
            include_str!(concat!(
                env!("CARGO_MANIFEST_DIR"),
                "/src/admin/templates/AdminModelList.vue"
            ))
            .into(),
        ),
        (
            "src/admin/AdminModelForm.vue".into(),
            include_str!(concat!(
                env!("CARGO_MANIFEST_DIR"),
                "/src/admin/templates/AdminModelForm.vue"
            ))
            .into(),
        ),
        (
            "src/admin/AdminModelTable.vue".into(),
            include_str!(concat!(
                env!("CARGO_MANIFEST_DIR"),
                "/src/admin/templates/AdminModelTable.vue"
            ))
            .into(),
        ),
        (
            "src/admin/admin.css".into(),
            include_str!(concat!(
                env!("CARGO_MANIFEST_DIR"),
                "/src/admin/templates/admin.css"
            ))
            .into(),
        ),
        (
            "src/admin/styles/tokens.css".into(),
            include_str!(concat!(
                env!("CARGO_MANIFEST_DIR"),
                "/src/admin/templates/styles/tokens.css"
            ))
            .into(),
        ),
        (
            "src/admin/styles/base.css".into(),
            include_str!(concat!(
                env!("CARGO_MANIFEST_DIR"),
                "/src/admin/templates/styles/base.css"
            ))
            .into(),
        ),
        (
            "src/admin/styles/components.css".into(),
            include_str!(concat!(
                env!("CARGO_MANIFEST_DIR"),
                "/src/admin/templates/styles/components.css"
            ))
            .into(),
        ),
        (
            "src/admin/components/GenericModelTable.vue".into(),
            include_str!(concat!(
                env!("CARGO_MANIFEST_DIR"),
                "/src/admin/templates/components/GenericModelTable.vue"
            ))
            .into(),
        ),
        (
            "src/admin/components/GenericModelForm.vue".into(),
            include_str!(concat!(
                env!("CARGO_MANIFEST_DIR"),
                "/src/admin/templates/components/GenericModelForm.vue"
            ))
            .into(),
        ),
        (
            "src/admin/components/AsyncRelationSelect.vue".into(),
            include_str!(concat!(
                env!("CARGO_MANIFEST_DIR"),
                "/src/admin/templates/components/AsyncRelationSelect.vue"
            ))
            .into(),
        ),
    ]);
    for endpoint in endpoints {
        let page = page_name(endpoint, endpoints);
        let api = api_name(endpoint, endpoints);
        files.push((format!("src/admin/pages/{page}List.vue"), format!("<script setup lang=\"ts\">import {{ {api}AdminModel }} from \"../generated/adminSchema\"; import GenericModelTable from \"../components/GenericModelTable.vue\";</script><template><GenericModelTable :model=\"{api}AdminModel\" /></template>\n")));
        files.push((format!("src/admin/pages/{page}Form.vue"), format!("<script setup lang=\"ts\">import {{ {api}AdminModel }} from \"../generated/adminSchema\"; import GenericModelForm from \"../components/GenericModelForm.vue\";</script><template><GenericModelForm :model=\"{api}AdminModel\" /></template>\n")));
    }
    files
}

fn admin_routes(endpoints: &[ApiEndpoint]) -> String {
    let mut out = HEADER.to_owned();
    out.push_str("import type { RouteRecordRaw } from \"vue-router\";\nimport AdminModelList from \"../AdminModelList.vue\";\n");
    for endpoint in endpoints {
        let page = page_name(endpoint, endpoints);
        out.push_str(&format!("import {page}List from \"../pages/{page}List.vue\";\nimport {page}Form from \"../pages/{page}Form.vue\";\n"));
    }
    out.push_str("\nexport const adminRoutes: RouteRecordRaw[] = [\n  { path: \"\", component: AdminModelList },\n");
    for endpoint in endpoints {
        let page = page_name(endpoint, endpoints);
        out.push_str(&format!("  {{ path: {}, component: {page}List }},\n  {{ path: {}, component: {page}Form }},\n  {{ path: {}, component: {page}Form }},\n", js(&endpoint.resource), js(&format!("{}/new", endpoint.resource)), js(&format!("{}/:id/edit", endpoint.resource))));
    }
    out.push_str("];\n");
    out
}

fn admin_type(rust_type: &str, relation: bool) -> &'static str {
    if relation || rust_type.contains("i64") {
        "integer"
    } else if rust_type == "bool" {
        "boolean"
    } else if rust_type.contains("OffsetDateTime") {
        "datetime"
    } else {
        "text"
    }
}
fn last_path_part(value: &str) -> &str {
    value.rsplit("::").next().unwrap_or(value).trim()
}
fn lower_first(value: &str) -> String {
    let mut chars = value.chars();
    chars
        .next()
        .map(|c| c.to_ascii_lowercase())
        .into_iter()
        .chain(chars)
        .collect()
}
fn api_name(endpoint: &ApiEndpoint, endpoints: &[ApiEndpoint]) -> String {
    if endpoints
        .iter()
        .filter(|item| item.model_name == endpoint.model_name)
        .count()
        == 1
    {
        return lower_first(&endpoint.model_name);
    }
    endpoint
        .resource
        .split('/')
        .next_back()
        .unwrap_or(&endpoint.resource)
        .trim_end_matches('s')
        .split('-')
        .enumerate()
        .map(|(index, part)| {
            if index == 0 {
                part.to_owned()
            } else {
                let mut chars = part.chars();
                chars
                    .next()
                    .map(|first| first.to_ascii_uppercase())
                    .into_iter()
                    .chain(chars)
                    .collect()
            }
        })
        .collect()
}
fn page_name(endpoint: &ApiEndpoint, endpoints: &[ApiEndpoint]) -> String {
    let name = if endpoints
        .iter()
        .filter(|item| item.model_name == endpoint.model_name)
        .count()
        == 1
    {
        endpoint.model_name.clone()
    } else {
        endpoint
            .resource
            .split('/')
            .next_back()
            .unwrap_or(&endpoint.resource)
            .trim_end_matches('s')
            .split('-')
            .map(|part| {
                let mut chars = part.chars();
                chars
                    .next()
                    .map(|first| first.to_ascii_uppercase())
                    .into_iter()
                    .chain(chars)
                    .collect::<String>()
            })
            .collect()
    };
    name
}
fn label(value: &str) -> String {
    value
        .replace("__", "_")
        .split('_')
        .map(|part| {
            let mut chars = part.chars();
            chars
                .next()
                .map(|c| c.to_ascii_uppercase().to_string() + chars.as_str())
                .unwrap_or_default()
        })
        .collect::<Vec<_>>()
        .join(" ")
}

fn filter_type(value: &str) -> &'static str {
    if value == "id" || value.ends_with("_id") {
        "integer"
    } else if value.ends_with("_at") {
        "datetime"
    } else {
        "text"
    }
}
fn js(value: &str) -> String {
    serde_json::to_string(value).expect("serializing string cannot fail")
}

#[cfg(test)]
mod tests {
    use super::*;

    fn endpoint(app_name: &'static str, model_name: &str) -> ApiEndpoint {
        ApiEndpoint {
            app_name,
            model_name: model_name.into(),
            resource: model_name.to_ascii_lowercase(),
            fields: Vec::new(),
            columns: Vec::new(),
            filters: Vec::new(),
            extensions: Vec::new(),
        }
    }

    #[test]
    fn groups_multiple_models_under_one_app() {
        let output = admin_schema(&[endpoint("tasks", "Task"), endpoint("tasks", "Note")]);
        assert_eq!(output.matches("name: \"tasks\"").count(), 1);
        assert!(output.contains("taskAdminModel"));
        assert!(output.contains("noteAdminModel"));
    }

    #[test]
    fn creates_static_project_files() {
        let files = static_files(&[endpoint("tasks", "Task")]);
        assert!(files.iter().any(|(path, _)| path == "package.json"));
        assert!(files.iter().any(|(path, _)| path == "tsconfig.json"));
        assert!(
            files
                .iter()
                .any(|(path, _)| path == "src/admin/pages/TaskList.vue")
        );
    }

    #[test]
    fn preserves_static_files_without_force() {
        let root = std::env::temp_dir().join(format!("che_rest_admin_test_{}", std::process::id()));
        let package = root.join("package.json");
        std::fs::create_dir_all(&root).unwrap();
        std::fs::write(&package, "custom").unwrap();
        generate(&root, &[endpoint("tasks", "Task")], false).unwrap();
        assert_eq!(std::fs::read_to_string(&package).unwrap(), "custom");
        generate(&root, &[endpoint("tasks", "Task")], true).unwrap();
        assert_ne!(std::fs::read_to_string(&package).unwrap(), "custom");
        let _ = std::fs::remove_dir_all(root);
    }
}
