use std::{
    fs,
    path::{Path, PathBuf},
};

use che_orm::{FieldType, Model, Schema, SqliteBackend, diff_schemas, sqlite_migration_sql};
use clap::{Parser, Subcommand};

use crate::{ApiEndpoint, ApiField, AppConfig, InstalledApps, ModuleContext, auth, openapi};

type ManageResult<T> = Result<T, Box<dyn std::error::Error>>;

const GENERATED_TS_HEADER: &str = "// This file is generated by che-rest. Do not edit manually.\n// Run the appropriate che-rest management generator to update it.\n\n";

#[derive(Debug, Parser)]
#[command(name = "manage")]
#[command(about = "Project management commands for che-rest applications")]
struct Cli {
    #[command(subcommand)]
    command: Command,
}

#[derive(Debug, Subcommand)]
enum Command {
    Startapp {
        name: String,

        #[arg(long, default_value = "src/apps")]
        apps_dir: PathBuf,

        #[arg(long = "model")]
        models: Vec<String>,
    },
    Makemigrations {
        app: String,

        #[arg(long, default_value = "src/apps")]
        apps_dir: PathBuf,

        #[arg(long, default_value = "auto")]
        name: String,
    },
    Migrate {
        app: Option<String>,

        #[arg(long, default_value = "src/apps")]
        apps_dir: PathBuf,

        #[arg(long, default_value = "app.toml")]
        config: PathBuf,

        #[arg(long)]
        database_url: Option<String>,
    },
    GenerateTs {
        #[arg(long, default_value = "src/generated")]
        out: PathBuf,
    },
    GenerateAdmin {
        #[arg(long, default_value = "frontend/admin")]
        out: PathBuf,

        #[arg(long)]
        templates_dir: Option<PathBuf>,

        #[arg(long)]
        force: bool,
    },
    GenerateOpenapi {
        #[arg(long, default_value = "openapi.json")]
        out: PathBuf,

        #[arg(long, default_value = "che-rest API")]
        title: String,

        #[arg(long, default_value = "0.1.0")]
        version: String,

        #[arg(long, default_value = "/api")]
        api_prefix: String,
    },
    Createsuperuser {
        #[arg(long, default_value = "app.toml")]
        config: PathBuf,

        #[arg(long)]
        database_url: Option<String>,

        #[arg(long)]
        username: String,

        #[arg(long)]
        password: String,
    },
}

pub struct Management {
    apps: InstalledApps,
}

impl Management {
    pub fn new(apps: InstalledApps) -> Self {
        Self { apps }
    }

    pub async fn run(self) -> ManageResult<()> {
        self.run_from(Cli::parse()).await
    }

    async fn run_from(self, cli: Cli) -> ManageResult<()> {
        match cli.command {
            Command::Startapp {
                name,
                apps_dir,
                models,
            } => startapp(&name, apps_dir, models)?,
            Command::Makemigrations {
                app,
                apps_dir,
                name,
            } => self.makemigrations(&app, apps_dir, &name)?,
            Command::Migrate {
                app,
                apps_dir,
                config,
                database_url,
            } => {
                self.migrate(app.as_deref(), apps_dir, config, database_url)
                    .await?
            }
            Command::GenerateTs { out } => self.generate_ts(out)?,
            Command::GenerateAdmin {
                out,
                templates_dir,
                force,
            } => self.generate_admin(out, templates_dir, force)?,
            Command::GenerateOpenapi {
                out,
                title,
                version,
                api_prefix,
            } => self.generate_openapi(out, title, version, api_prefix)?,
            Command::Createsuperuser {
                config,
                database_url,
                username,
                password,
            } => createsuperuser(config, database_url, &username, &password).await?,
        }

        Ok(())
    }

    fn generate_openapi(
        &self,
        out: PathBuf,
        title: String,
        version: String,
        api_prefix: String,
    ) -> ManageResult<()> {
        let spec = openapi::openapi_json(
            &self.api_endpoints(),
            openapi::OpenApiOptions {
                title,
                version,
                api_prefix,
            },
        );
        if let Some(parent) = out.parent().filter(|parent| !parent.as_os_str().is_empty()) {
            fs::create_dir_all(parent)?;
        }
        fs::write(&out, serde_json::to_string_pretty(&spec)?)?;

        println!("Generated OpenAPI schema in {}", out.display());
        Ok(())
    }

    fn makemigrations(&self, app: &str, apps_dir: PathBuf, name: &str) -> ManageResult<()> {
        validate_app_name(app)?;
        let module = self
            .apps
            .find(app)
            .ok_or_else(|| format!("app is not installed: {app}"))?;

        let migrations_dir = app_migrations_dir(&apps_dir, app);
        fs::create_dir_all(&migrations_dir)?;

        let snapshot_path = migrations_dir.join("schema.json");
        let old_schema = Schema::load_or_empty(&snapshot_path)?;
        let new_schema = app_schema(module);
        let migration = diff_schemas(&old_schema, &new_schema);

        if migration.changes.is_empty() {
            println!("No schema changes detected for app {app}");
            return Ok(());
        }

        let sql = sqlite_migration_sql(&migration);
        let file_name = format!(
            "{:04}_{}.sql",
            next_migration_number(&migrations_dir)?,
            slugify(name)
        );
        let migration_path = migrations_dir.join(file_name);
        fs::write(&migration_path, format!("{sql}\n"))?;
        new_schema.save(snapshot_path)?;

        println!("Created {}", migration_path.display());

        Ok(())
    }

    async fn migrate(
        &self,
        app: Option<&str>,
        apps_dir: PathBuf,
        config: PathBuf,
        database_url: Option<String>,
    ) -> ManageResult<()> {
        let database_url = match database_url {
            Some(database_url) => database_url,
            None => AppConfig::from_file(config)?.database.url,
        };
        let db = SqliteBackend::connect(&database_url).await?;

        match app {
            Some(app) => {
                validate_app_name(app)?;
                if self.apps.find(app).is_none() {
                    return Err(format!("app is not installed: {app}").into());
                }
                apply_app_migrations(&db, &apps_dir, app).await?;
            }
            None => {
                for app in self.apps.names() {
                    apply_app_migrations(&db, &apps_dir, app).await?;
                }
            }
        }

        Ok(())
    }

    fn generate_ts(&self, out: PathBuf) -> ManageResult<()> {
        let endpoints = self.api_endpoints();
        fs::create_dir_all(&out)?;
        fs::write(out.join("api_client.ts"), api_client_ts())?;
        fs::write(out.join("models.ts"), models_ts(&endpoints))?;
        fs::write(out.join("api.ts"), api_ts(&endpoints))?;
        fs::write(out.join("useModelList.ts"), use_model_list_ts())?;
        fs::write(out.join("useModelItem.ts"), use_model_item_ts())?;

        println!("Generated TypeScript API in {}", out.display());
        Ok(())
    }

    fn generate_admin(
        &self,
        out: PathBuf,
        templates_dir: Option<PathBuf>,
        force: bool,
    ) -> ManageResult<()> {
        let api_endpoints = self.api_endpoints();
        let admin_endpoints = self.admin_endpoints();
        let admin_pages = admin_pages(&admin_endpoints);
        fs::create_dir_all(&out)?;

        for template in ADMIN_TEMPLATES {
            write_admin_template(&out, templates_dir.as_deref(), template, force)?;
        }

        for page in &admin_pages {
            write_admin_page(&out, page, AdminPageKind::List, force)?;
            write_admin_page(&out, page, AdminPageKind::Form, force)?;
        }

        write_generated_file(
            &out.join("src/admin/generated/adminSchema.ts"),
            &admin_schema_ts(&admin_endpoints),
        )?;
        write_generated_file(
            &out.join("src/admin/generated/adminRoutes.ts"),
            &admin_routes_ts(&admin_pages),
        )?;
        write_generated_file(
            &out.join("src/admin/adminSchema.ts"),
            &admin_schema_compat_ts(),
        )?;
        write_generated_file(&out.join("src/generated/api_client.ts"), api_client_ts())?;
        write_generated_file(
            &out.join("src/generated/models.ts"),
            &models_ts(&api_endpoints),
        )?;
        write_generated_file(&out.join("src/generated/api.ts"), &api_ts(&api_endpoints))?;
        write_generated_file(
            &out.join("src/generated/useModelList.ts"),
            use_model_list_ts(),
        )?;
        write_generated_file(
            &out.join("src/generated/useModelItem.ts"),
            use_model_item_ts(),
        )?;

        if force {
            println!("Generated Vue admin project in {}", out.display());
        } else {
            println!("Updated generated Vue admin files in {}", out.display());
        }
        Ok(())
    }

    fn api_endpoints(&self) -> Vec<ApiEndpoint> {
        let mut endpoints = Vec::new();
        for module in self.apps.iter() {
            let mut ctx = ModuleContext::new();
            module.init(&mut ctx);
            endpoints.extend(ctx.api_endpoints().iter().cloned());
        }
        endpoints.sort_by(|left, right| left.model_name.cmp(&right.model_name));
        endpoints
    }

    fn admin_endpoints(&self) -> Vec<AdminEndpoint> {
        let mut endpoints = Vec::new();
        for module in self.apps.iter() {
            let mut ctx = ModuleContext::new();
            module.init(&mut ctx);
            endpoints.extend(
                ctx.api_endpoints()
                    .iter()
                    .cloned()
                    .map(|endpoint| AdminEndpoint {
                        app_name: module.name().to_string(),
                        endpoint,
                    }),
            );
        }
        endpoints.sort_by(|left, right| {
            left.app_name
                .cmp(&right.app_name)
                .then_with(|| left.endpoint.model_name.cmp(&right.endpoint.model_name))
        });
        endpoints
    }
}

#[derive(Debug, Clone)]
struct AdminEndpoint {
    app_name: String,
    endpoint: ApiEndpoint,
}

struct AdminPage {
    app_name: String,
    resource: String,
    base_name: String,
    model_const: String,
}

enum AdminPageKind {
    List,
    Form,
}

struct AdminTemplate {
    path: &'static str,
    content: &'static str,
}

static ADMIN_TEMPLATES: &[AdminTemplate] = &[
    AdminTemplate {
        path: "package.json",
        content: include_str!("admin/templates/package.json"),
    },
    AdminTemplate {
        path: "index.html",
        content: include_str!("admin/templates/index.html"),
    },
    AdminTemplate {
        path: "vite.config.ts",
        content: include_str!("admin/templates/vite.config.ts"),
    },
    AdminTemplate {
        path: "tsconfig.json",
        content: include_str!("admin/templates/tsconfig.json"),
    },
    AdminTemplate {
        path: ".env.example",
        content: include_str!("admin/templates/.env.example"),
    },
    AdminTemplate {
        path: "src/main.ts",
        content: include_str!("admin/templates/src/main.ts"),
    },
    AdminTemplate {
        path: "src/App.vue",
        content: include_str!("admin/templates/src/App.vue"),
    },
    AdminTemplate {
        path: "src/router.ts",
        content: include_str!("admin/templates/src/router.ts"),
    },
    AdminTemplate {
        path: "src/admin/AdminApp.vue",
        content: include_str!("admin/templates/src/admin/AdminApp.vue"),
    },
    AdminTemplate {
        path: "src/admin/AdminLogin.vue",
        content: include_str!("admin/templates/src/admin/AdminLogin.vue"),
    },
    AdminTemplate {
        path: "src/admin/AdminModelList.vue",
        content: include_str!("admin/templates/src/admin/AdminModelList.vue"),
    },
    AdminTemplate {
        path: "src/admin/AdminModelTable.vue",
        content: include_str!("admin/templates/src/admin/AdminModelTable.vue"),
    },
    AdminTemplate {
        path: "src/admin/AdminModelForm.vue",
        content: include_str!("admin/templates/src/admin/AdminModelForm.vue"),
    },
    AdminTemplate {
        path: "src/admin/components/GenericModelTable.vue",
        content: include_str!("admin/templates/src/admin/components/GenericModelTable.vue"),
    },
    AdminTemplate {
        path: "src/admin/components/GenericModelForm.vue",
        content: include_str!("admin/templates/src/admin/components/GenericModelForm.vue"),
    },
    AdminTemplate {
        path: "src/admin/components/AsyncRelationSelect.vue",
        content: include_str!("admin/templates/src/admin/components/AsyncRelationSelect.vue"),
    },
    AdminTemplate {
        path: "src/admin/adminRoutes.ts",
        content: include_str!("admin/templates/src/admin/adminRoutes.ts"),
    },
    AdminTemplate {
        path: "src/admin/admin.css",
        content: include_str!("admin/templates/src/admin/admin.css"),
    },
    AdminTemplate {
        path: "src/admin/styles/tokens.css",
        content: include_str!("admin/templates/src/admin/styles/tokens.css"),
    },
    AdminTemplate {
        path: "src/admin/styles/base.css",
        content: include_str!("admin/templates/src/admin/styles/base.css"),
    },
    AdminTemplate {
        path: "src/admin/styles/components.css",
        content: include_str!("admin/templates/src/admin/styles/components.css"),
    },
];

fn write_admin_template(
    out: &Path,
    templates_dir: Option<&Path>,
    template: &AdminTemplate,
    force: bool,
) -> ManageResult<()> {
    let target = out.join(template.path);
    if target.exists() && !force {
        return Ok(());
    }

    if let Some(templates_dir) = templates_dir {
        let override_path = templates_dir.join(template.path);
        if override_path.exists() {
            let content = fs::read_to_string(override_path)?;
            return write_generated_file(&target, &content);
        }
    }

    write_generated_file(&target, template.content)
}

fn write_generated_file(path: &Path, content: &str) -> ManageResult<()> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(path, content)?;
    Ok(())
}

fn write_admin_page(
    out: &Path,
    page: &AdminPage,
    kind: AdminPageKind,
    force: bool,
) -> ManageResult<()> {
    let (component_name, generic_component) = match kind {
        AdminPageKind::List => (format!("{}List", page.base_name), "GenericModelTable"),
        AdminPageKind::Form => (format!("{}Form", page.base_name), "GenericModelForm"),
    };
    let target = out.join(format!("src/admin/pages/{component_name}.vue"));
    if target.exists() && !force {
        return Ok(());
    }

    let content = format!(
        r#"<script setup lang="ts">
import {{ {model_const} }} from "../generated/adminSchema";
import {generic_component} from "../components/{generic_component}.vue";
</script>

<template>
  <{generic_component} :model="{model_const}" />
</template>
"#,
        model_const = page.model_const,
        generic_component = generic_component,
    );
    write_generated_file(&target, &content)
}

fn admin_pages(endpoints: &[AdminEndpoint]) -> Vec<AdminPage> {
    endpoints
        .iter()
        .map(|admin_endpoint| {
            let base_name = admin_page_base_name(admin_endpoint, endpoints);
            AdminPage {
                app_name: admin_endpoint.app_name.clone(),
                resource: admin_endpoint.endpoint.resource.clone(),
                model_const: format!("{}AdminModel", lower_first(&base_name)),
                base_name,
            }
        })
        .collect()
}

fn admin_page_base_name(admin_endpoint: &AdminEndpoint, endpoints: &[AdminEndpoint]) -> String {
    let model_name = &admin_endpoint.endpoint.model_name;
    let duplicates = endpoints
        .iter()
        .filter(|candidate| candidate.endpoint.model_name == *model_name)
        .count();
    if duplicates > 1 {
        format!("{}{}", camel_case(&admin_endpoint.app_name), model_name)
    } else {
        model_name.clone()
    }
}

async fn createsuperuser(
    config: PathBuf,
    database_url: Option<String>,
    username: &str,
    password: &str,
) -> ManageResult<()> {
    let database_url = match database_url {
        Some(database_url) => database_url,
        None => AppConfig::from_file(config)?.database.url,
    };
    let db = SqliteBackend::connect(&database_url).await?;
    db.create_table::<auth::models::User>().await?;
    db.create_table::<auth::models::AuthToken>().await?;
    db.create_table::<auth::models::AuthSession>().await?;

    let existing = auth::models::User::objects(&db)
        .query()
        .eq("username", username)
        .limit(1)
        .all()
        .await?;
    if !existing.is_empty() {
        return Err(format!("user already exists: {username}").into());
    }

    let password_hash = auth::models::hash_password(password)
        .map_err(|error| format!("failed to hash password: {error}"))?;
    auth::models::User::objects(&db)
        .create()
        .set("username", username)
        .set("password_hash", password_hash)
        .set("is_active", true)
        .set("is_staff", true)
        .set("is_admin", true)
        .set("is_superuser", true)
        .execute()
        .await?;

    println!("Created superuser {username}");
    Ok(())
}

fn app_schema(module: &dyn crate::AppModule) -> Schema {
    let mut ctx = ModuleContext::new();
    module.init(&mut ctx);
    Schema::from_models(ctx.model_schemas().to_vec())
}

fn models_ts(endpoints: &[ApiEndpoint]) -> String {
    let mut out = String::from(GENERATED_TS_HEADER);
    out.push_str("import type { ListParams } from \"./api_client\";\n\n");

    for endpoint in endpoints {
        out.push_str(&format!("export interface {} {{\n", endpoint.model_name));
        for field in endpoint.fields.iter().filter(|field| !field.write_only) {
            out.push_str(&format!("  {}: {};\n", field.name, response_ts_type(field)));
        }
        out.push_str("}\n\n");

        out.push_str(&format!(
            "export interface {}Create {{\n",
            endpoint.model_name
        ));
        for field in endpoint.fields.iter().filter(|field| !field.read_only) {
            out.push_str(&format!(
                "  {}{}: {};\n",
                field.name,
                optional_marker(field),
                ts_type(field.ty, field.nullable)
            ));
        }
        out.push_str("}\n\n");

        out.push_str(&format!(
            "export interface {}Update {{\n",
            endpoint.model_name
        ));
        for field in endpoint.fields.iter().filter(|field| !field.read_only) {
            out.push_str(&format!(
                "  {}?: {};\n",
                field.name,
                ts_type(field.ty, field.nullable)
            ));
        }
        out.push_str("}\n\n");

        out.push_str(&format!(
            "export interface {}ListParams extends ListParams {{\n",
            endpoint.model_name
        ));
        for filter in &endpoint.filters {
            out.push_str(&format!(
                "  {}?: {};\n",
                filter.name,
                ts_type(filter.ty, filter.nullable)
            ));
        }
        out.push_str("}\n\n");
    }

    out
}

fn api_ts(endpoints: &[ApiEndpoint]) -> String {
    let mut out = String::from(GENERATED_TS_HEADER);
    out.push_str("import { createModelApi } from \"./api_client\";\n");

    if endpoints.is_empty() {
        out.push('\n');
        return out;
    }

    out.push_str("import type {\n");
    for endpoint in endpoints {
        out.push_str(&format!("  {},\n", endpoint.model_name));
        out.push_str(&format!("  {}Create,\n", endpoint.model_name));
        out.push_str(&format!("  {}Update,\n", endpoint.model_name));
        out.push_str(&format!("  {}ListParams,\n", endpoint.model_name));
    }
    out.push_str("} from \"./models\";\n\n");

    for endpoint in endpoints {
        out.push_str(&format!(
            "export const {}Api = createModelApi<{}, {}Create, {}Update, {}ListParams>(\"{}\");\n",
            lower_first(&endpoint.model_name),
            endpoint.model_name,
            endpoint.model_name,
            endpoint.model_name,
            endpoint.model_name,
            endpoint.resource
        ));
    }

    out
}

fn optional_marker(field: &ApiField) -> &'static str {
    if field.required && !field.has_default {
        ""
    } else {
        "?"
    }
}

fn ts_type(ty: FieldType, nullable: bool) -> String {
    let base = match ty {
        FieldType::Integer | FieldType::Real => "number",
        FieldType::Text | FieldType::DateTime | FieldType::Choice => "string",
        FieldType::Boolean => "boolean",
        FieldType::Json => "unknown",
    };
    if nullable {
        format!("{base} | null")
    } else {
        base.to_string()
    }
}

fn response_ts_type(field: &ApiField) -> String {
    match &field.related_model {
        Some(model) if field.nullable => format!("{model} | null"),
        Some(model) => model.clone(),
        None => ts_type(field.ty, field.nullable),
    }
}

fn lower_first(value: &str) -> String {
    let mut chars = value.chars();
    match chars.next() {
        Some(first) => first.to_ascii_lowercase().to_string() + chars.as_str(),
        None => String::new(),
    }
}

fn api_client_ts() -> &'static str {
    r#"// This file is generated by che-rest. Do not edit manually.
// Run the appropriate che-rest management generator to update it.

import axios from "axios";

export interface BaseEntity {
  id?: number;
}

export interface ListParams {
  ordering?: string;
  limit?: number;
  offset?: number;
  [key: string]: string | number | boolean | null | undefined;
}

export interface PaginatedResponse<T> {
  count: number;
  results: T[];
}

export interface ModelApi<
  T extends BaseEntity,
  CreateDTO = Partial<T>,
  UpdateDTO = Partial<T>,
  Params extends ListParams = ListParams,
> {
  list: (params?: Params) => Promise<PaginatedResponse<T>>;
  retrieve: (id: number) => Promise<T>;
  create: (payload: CreateDTO) => Promise<T>;
  update: (id: number, payload: UpdateDTO) => Promise<T>;
  remove: (id: number) => Promise<void>;
}

export const apiClient = axios.create({
  baseURL: import.meta.env.VITE_API_BASE_URL ?? "/api",
  withCredentials: true,
  xsrfCookieName: "che_rest_csrf",
  xsrfHeaderName: "X-CSRF-Token",
  headers: {
    "Content-Type": "application/json",
  },
});

let authToken: string | null = null;

export function setAuthToken(token: string | null) {
  authToken = token;
}

apiClient.interceptors.request.use((config) => {
  if (authToken) {
    config.headers.Authorization = `Token ${authToken}`;
  } else {
    delete config.headers.Authorization;
  }
  return config;
});

export function createModelApi<
  T extends BaseEntity,
  CreateDTO = Partial<T>,
  UpdateDTO = Partial<T>,
  Params extends ListParams = ListParams,
>(resource: string): ModelApi<T, CreateDTO, UpdateDTO, Params> {
  const normalized = resource.endsWith("/") ? resource : `${resource}/`;

  return {
    async list(params) {
      const response = await apiClient.get<PaginatedResponse<T>>(normalized, { params });
      return response.data;
    },

    async retrieve(id) {
      const response = await apiClient.get<T>(`${normalized}${id}/`);
      return response.data;
    },

    async create(payload) {
      const response = await apiClient.post<T>(normalized, payload);
      return response.data;
    },

    async update(id, payload) {
      const response = await apiClient.patch<T>(`${normalized}${id}/`, payload);
      return response.data;
    },

    async remove(id) {
      await apiClient.delete(`${normalized}${id}/`);
    },
  };
}
"#
}

fn use_model_list_ts() -> &'static str {
    r#"// This file is generated by che-rest. Do not edit manually.
// Run the appropriate che-rest management generator to update it.

import { onMounted, reactive, ref, shallowRef, watch } from "vue";
import type { BaseEntity, ListParams, ModelApi } from "./api_client";

export interface UseModelListOptions<Params extends ListParams> {
  defaultFilters?: Partial<Params>;
  autoLoad?: boolean;
  reloadOnFilterChange?: boolean;
  debounceMs?: number;
  onError?: (message: string, error: unknown) => void;
}

export function useModelList<
  T extends BaseEntity,
  CreateDTO = Partial<T>,
  UpdateDTO = Partial<T>,
  Params extends ListParams = ListParams,
>(api: ModelApi<T, CreateDTO, UpdateDTO, Params>, options: UseModelListOptions<Params> = {}) {
  const items = shallowRef<T[]>([]);
  const filters = reactive({ ...(options.defaultFilters ?? {}) } as Params) as Params;
  const count = ref(0);
  const loading = ref(false);
  const error = ref("");
  let loadTimer: ReturnType<typeof setTimeout> | undefined;
  let skipNextFilterReload = false;

  async function load(params?: Partial<Params>) {
    if (params) {
      skipNextFilterReload = true;
      Object.assign(filters, params);
    }

    loading.value = true;
    error.value = "";

    try {
      const response = await api.list(cleanParams(filters) as Params);
      items.value = response.results;
      count.value = response.count;
      return response;
    } catch (err) {
      handleError(err, "Unable to load objects");
      return null;
    } finally {
      loading.value = false;
    }
  }

  async function remove(id: number) {
    loading.value = true;
    error.value = "";

    try {
      await api.remove(id);
      await load();
      return true;
    } catch (err) {
      handleError(err, "Unable to delete object");
      return false;
    } finally {
      loading.value = false;
    }
  }

  function scheduleLoad() {
    clearTimeout(loadTimer);
    loadTimer = setTimeout(() => {
      load();
    }, options.debounceMs ?? 250);
  }

  function handleError(err: unknown, fallback: string) {
    const message = errorMessage(err, fallback);
    error.value = message;
    options.onError?.(message, err);
  }

  if (options.reloadOnFilterChange) {
    watch(filters, () => {
      if (skipNextFilterReload) {
        skipNextFilterReload = false;
        return;
      }

      scheduleLoad();
    });
  }

  if (options.autoLoad) {
    onMounted(() => {
      load();
    });
  }

  return {
    items,
    filters,
    count,
    loading,
    error,
    load,
    remove,
  };
}

function cleanParams(params: ListParams) {
  const clean: ListParams = {};

  for (const [key, value] of Object.entries(params)) {
    if (value !== "" && value !== null && value !== undefined) {
      clean[key] = value;
    }
  }

  return clean;
}

function errorMessage(err: unknown, fallback: string) {
  if (typeof err === "object" && err && "detail" in err) {
    return String((err as { detail: unknown }).detail);
  }

  if (err instanceof Error) {
    return err.message;
  }

  return fallback;
}
"#
}

fn use_model_item_ts() -> &'static str {
    r#"// This file is generated by che-rest. Do not edit manually.
// Run the appropriate che-rest management generator to update it.

import { ref, shallowRef } from "vue";
import type { BaseEntity, ListParams, ModelApi } from "./api_client";

export interface UseModelItemOptions {
  onError?: (message: string, error: unknown) => void;
}

export function useModelItem<
  T extends BaseEntity,
  CreateDTO = Partial<T>,
  UpdateDTO = Partial<T>,
  Params extends ListParams = ListParams,
>(api: ModelApi<T, CreateDTO, UpdateDTO, Params>, options: UseModelItemOptions = {}) {
  const item = shallowRef<T | null>(null);
  const loading = ref(false);
  const error = ref("");

  async function retrieve(id: number) {
    loading.value = true;
    error.value = "";

    try {
      item.value = await api.retrieve(id);
      return item.value;
    } catch (err) {
      handleError(err, "Unable to load object");
      return null;
    } finally {
      loading.value = false;
    }
  }

  async function create(payload: CreateDTO) {
    loading.value = true;
    error.value = "";

    try {
      item.value = await api.create(payload);
      return item.value;
    } catch (err) {
      handleError(err, "Unable to create object");
      return null;
    } finally {
      loading.value = false;
    }
  }

  async function update(id: number, payload: UpdateDTO) {
    loading.value = true;
    error.value = "";

    try {
      item.value = await api.update(id, payload);
      return item.value;
    } catch (err) {
      handleError(err, "Unable to update object");
      return null;
    } finally {
      loading.value = false;
    }
  }

  async function remove(id: number) {
    loading.value = true;
    error.value = "";

    try {
      await api.remove(id);
      item.value = null;
      return true;
    } catch (err) {
      handleError(err, "Unable to delete object");
      return false;
    } finally {
      loading.value = false;
    }
  }

  function handleError(err: unknown, fallback: string) {
    const message = errorMessage(err, fallback);
    error.value = message;
    options.onError?.(message, err);
  }

  return {
    item,
    loading,
    error,
    retrieve,
    create,
    update,
    remove,
  };
}

function errorMessage(err: unknown, fallback: string) {
  if (typeof err === "object" && err && "detail" in err) {
    return String((err as { detail: unknown }).detail);
  }

  if (err instanceof Error) {
    return err.message;
  }

  return fallback;
}
"#
}

fn admin_schema_ts(endpoints: &[AdminEndpoint]) -> String {
    let mut out = String::from(GENERATED_TS_HEADER);

    if endpoints.is_empty() {
        out.push_str(
            "export type AdminFieldType = \"integer\" | \"text\" | \"boolean\" | \"real\" | \"datetime\";\n\n",
        );
        out.push_str(admin_schema_types_ts());
        out.push_str("export const adminModels: AdminModel[] = [];\n");
        out.push_str("export const adminApps: AdminApp[] = [];\n");
        return out;
    }

    out.push_str("import {\n");
    for admin_endpoint in endpoints {
        let endpoint = &admin_endpoint.endpoint;
        out.push_str(&format!("  {}Api,\n", lower_first(&endpoint.model_name)));
    }
    out.push_str("} from \"../../generated/api\";\n\n");
    out.push_str(
        "export type AdminFieldType = \"integer\" | \"text\" | \"boolean\" | \"real\" | \"datetime\";\n\n",
    );
    out.push_str(admin_schema_types_ts());
    out.push_str("export const adminModels: AdminModel[] = [\n");

    for admin_endpoint in endpoints {
        let endpoint = &admin_endpoint.endpoint;
        out.push_str("  {\n");
        out.push_str(&format!(
            "    appName: {},\n",
            js_string(&admin_endpoint.app_name)
        ));
        out.push_str(&format!("    name: {},\n", js_string(&endpoint.model_name)));
        out.push_str(&format!(
            "    resource: {},\n",
            js_string(&endpoint.resource)
        ));
        out.push_str(&format!(
            "    api: {}Api,\n",
            lower_first(&endpoint.model_name)
        ));
        out.push_str("    fields: [\n");
        for field in &endpoint.fields {
            let relation_field = endpoint
                .fields
                .iter()
                .find(|candidate| {
                    candidate.source == field.source
                        && candidate.related_model.is_some()
                        && candidate.read_only
                        && candidate.name != field.name
                })
                .map(|candidate| candidate.name.as_str());
            let related_model = field.related_model.as_deref().or_else(|| {
                endpoint
                    .fields
                    .iter()
                    .find(|candidate| {
                        candidate.source == field.source
                            && candidate.related_model.is_some()
                            && candidate.read_only
                    })
                    .and_then(|candidate| candidate.related_model.as_deref())
            });

            out.push_str("      {\n");
            out.push_str(&format!("        name: {},\n", js_string(&field.name)));
            out.push_str(&format!("        source: {},\n", js_string(&field.source)));
            out.push_str(&format!(
                "        type: {},\n",
                js_string(admin_field_type(field.ty))
            ));
            out.push_str(&format!(
                "        label: {},\n",
                js_string(&human_label(&field.name))
            ));
            out.push_str(&format!("        readOnly: {},\n", field.read_only));
            out.push_str(&format!("        writeOnly: {},\n", field.write_only));
            out.push_str(&format!("        required: {},\n", field.required));
            out.push_str(&format!("        nullable: {},\n", field.nullable));
            out.push_str(&format!("        hasDefault: {},\n", field.has_default));
            if let Some(choices) = &field.choices {
                out.push_str(&format!(
                    "        choices: {},\n",
                    serde_json::to_string(choices).expect("serializing choices cannot fail")
                ));
            }
            if let Some(model) = related_model {
                out.push_str(&format!("        relatedModel: {},\n", js_string(model)));
            }
            if let Some(relation_field) = relation_field {
                out.push_str(&format!(
                    "        relationField: {},\n",
                    js_string(relation_field)
                ));
            }
            out.push_str("      },\n");
        }
        out.push_str("    ],\n");
        out.push_str("    filters: [\n");
        for filter in &endpoint.filters {
            out.push_str("      {\n");
            out.push_str(&format!("        name: {},\n", js_string(&filter.name)));
            out.push_str(&format!("        source: {},\n", js_string(&filter.source)));
            out.push_str(&format!(
                "        type: {},\n",
                js_string(admin_field_type(filter.ty))
            ));
            out.push_str(&format!(
                "        label: {},\n",
                js_string(&human_label(&filter.name))
            ));
            out.push_str(&format!("        nullable: {},\n", filter.nullable));
            out.push_str("      },\n");
        }
        out.push_str("    ],\n");
        out.push_str("  },\n");
    }

    out.push_str("];\n");

    for page in admin_pages(endpoints) {
        out.push_str(&format!(
            "\nexport const {} = adminModels.find((model) => model.appName === {} && model.resource === {}) as AdminModel;\n",
            page.model_const,
            js_string(&page.app_name),
            js_string(&page.resource)
        ));
    }

    out.push_str("\nexport const adminApps: AdminApp[] = [\n");

    let mut current_app: Option<&str> = None;
    for admin_endpoint in endpoints {
        if current_app == Some(admin_endpoint.app_name.as_str()) {
            continue;
        }

        current_app = Some(admin_endpoint.app_name.as_str());
        out.push_str("  {\n");
        out.push_str(&format!(
            "    name: {},\n",
            js_string(&admin_endpoint.app_name)
        ));
        out.push_str("    models: adminModels.filter((model) => model.appName === ");
        out.push_str(&js_string(&admin_endpoint.app_name));
        out.push_str("),\n");
        out.push_str("  },\n");
    }

    out.push_str("];\n");
    out
}

fn admin_schema_compat_ts() -> String {
    let mut out = String::from(GENERATED_TS_HEADER);
    out.push_str("export * from \"./generated/adminSchema\";\n");
    out
}

fn admin_routes_ts(pages: &[AdminPage]) -> String {
    let mut out = String::from(GENERATED_TS_HEADER);
    out.push_str("import type { RouteRecordRaw } from \"vue-router\";\n");
    out.push_str("import AdminModelList from \"../AdminModelList.vue\";\n");

    for page in pages {
        out.push_str(&format!(
            "import {}List from \"../pages/{}List.vue\";\n",
            page.base_name, page.base_name
        ));
        out.push_str(&format!(
            "import {}Form from \"../pages/{}Form.vue\";\n",
            page.base_name, page.base_name
        ));
    }

    out.push_str("\nexport const adminRoutes: RouteRecordRaw[] = [\n");
    out.push_str("  { path: \"\", component: AdminModelList },\n");
    for page in pages {
        out.push_str(&format!(
            "  {{ path: {}, component: {}List }},\n",
            js_string(&page.resource),
            page.base_name
        ));
        out.push_str(&format!(
            "  {{ path: {}, component: {}Form }},\n",
            js_string(&format!("{}/new", page.resource)),
            page.base_name
        ));
        out.push_str(&format!(
            "  {{ path: {}, component: {}Form }},\n",
            js_string(&format!("{}/:id/edit", page.resource)),
            page.base_name
        ));
    }
    out.push_str("];\n");
    out
}

fn admin_schema_types_ts() -> &'static str {
    r#"export interface AdminField {
  name: string;
  source: string;
  type: AdminFieldType;
  label: string;
  readOnly: boolean;
  writeOnly: boolean;
  required: boolean;
  nullable: boolean;
  hasDefault: boolean;
  choices?: string[];
  relatedModel?: string;
  relationField?: string;
}

export interface AdminFilter {
  name: string;
  source: string;
  type: AdminFieldType;
  label: string;
  nullable: boolean;
}

export interface AdminModelApi {
  list: (params?: any) => Promise<{ count: number; results: any[] }>;
  retrieve: (id: number) => Promise<any>;
  create: (payload: any) => Promise<any>;
  update: (id: number, payload: any) => Promise<any>;
  remove: (id: number) => Promise<void>;
}

export interface AdminModel {
  appName: string;
  name: string;
  resource: string;
  api: AdminModelApi;
  fields: AdminField[];
  filters: AdminFilter[];
}

export interface AdminApp {
  name: string;
  models: AdminModel[];
}

"#
}

#[allow(dead_code)]
fn admin_app_vue() -> &'static str {
    r#"<script setup lang="ts">
import { adminApps } from "./adminSchema";
</script>

<template>
  <section class="che-admin">
    <aside class="che-admin-sidebar">
      <RouterLink class="che-admin-brand" to="/admin">Admin</RouterLink>
      <nav class="che-admin-nav">
        <section v-for="app in adminApps" :key="app.name" class="che-admin-nav-group">
          <p>{{ app.name }}</p>
          <RouterLink
            v-for="model in app.models"
            :key="model.resource"
            :to="`/admin/${model.resource}`"
          >
            {{ model.name }}
          </RouterLink>
        </section>
      </nav>
    </aside>

    <main class="che-admin-main">
      <RouterView />
    </main>
  </section>
</template>

<style scoped>
.che-admin {
  display: grid;
  grid-template-columns: 220px minmax(0, 1fr);
  min-height: calc(100vh - 72px);
  background: #f6f7fb;
  color: #172033;
}

.che-admin-sidebar {
  border-right: 1px solid #dde2ee;
  background: #ffffff;
  padding: 24px;
}

.che-admin-brand {
  color: #172033;
  display: inline-flex;
  font-size: 20px;
  font-weight: 800;
  margin-bottom: 24px;
  text-decoration: none;
}

.che-admin-nav {
  display: grid;
  gap: 18px;
}

.che-admin-nav-group {
  display: grid;
  gap: 8px;
}

.che-admin-nav-group p {
  color: #64708a;
  font-size: 12px;
  font-weight: 800;
  letter-spacing: 0.08em;
  margin: 0 0 2px;
  text-transform: uppercase;
}

.che-admin-nav-group a {
  border-radius: 10px;
  color: #4f5b73;
  padding: 10px 12px;
  text-decoration: none;
}

.che-admin-nav-group a.router-link-active {
  background: #edf2ff;
  color: #2446c6;
  font-weight: 700;
}

.che-admin-main {
  min-width: 0;
  padding: 32px;
}

@media (max-width: 760px) {
  .che-admin {
    grid-template-columns: 1fr;
  }

  .che-admin-sidebar {
    border-right: 0;
    border-bottom: 1px solid #dde2ee;
  }
}
</style>
"#
}

#[allow(dead_code)]
fn admin_model_list_vue() -> &'static str {
    r#"<script setup lang="ts">
import { adminApps } from "./adminSchema";
</script>

<template>
  <section class="admin-panel">
    <div class="admin-heading">
      <p>Generated admin</p>
      <h1>Models</h1>
    </div>

    <section v-for="app in adminApps" :key="app.name" class="app-group">
      <div class="app-heading">
        <h2>{{ app.name }}</h2>
        <span>{{ app.models.length }} models</span>
      </div>

      <div class="model-grid">
        <RouterLink
          v-for="model in app.models"
          :key="model.resource"
          class="model-card"
          :to="`/admin/${model.resource}`"
        >
          <span>{{ model.name }}</span>
          <small>{{ model.resource }}</small>
        </RouterLink>
      </div>
    </section>
  </section>
</template>

<style scoped>
.admin-panel {
  display: grid;
  gap: 24px;
}

.admin-heading p {
  color: #64708a;
  font-size: 13px;
  font-weight: 700;
  letter-spacing: 0.08em;
  margin: 0 0 4px;
  text-transform: uppercase;
}

.admin-heading h1 {
  font-size: 34px;
  margin: 0;
}

.app-group {
  display: grid;
  gap: 14px;
}

.app-heading {
  align-items: end;
  display: flex;
  gap: 10px;
}

.app-heading h2 {
  font-size: 22px;
  margin: 0;
}

.app-heading span {
  color: #64708a;
  font-size: 13px;
  padding-bottom: 2px;
}

.model-grid {
  display: grid;
  gap: 16px;
  grid-template-columns: repeat(auto-fit, minmax(180px, 1fr));
}

.model-card {
  background: #ffffff;
  border: 1px solid #dde2ee;
  border-radius: 18px;
  box-shadow: 0 12px 36px rgba(23, 32, 51, 0.08);
  color: #172033;
  display: grid;
  gap: 6px;
  padding: 20px;
  text-decoration: none;
}

.model-card span {
  font-size: 20px;
  font-weight: 800;
}

.model-card small {
  color: #64708a;
}
</style>
"#
}

#[allow(dead_code)]
fn admin_model_table_vue() -> &'static str {
    r#"<script setup lang="ts">
import { computed, ref, watch } from "vue";
import { useRoute, useRouter } from "vue-router";
import { adminModels, type AdminFilter } from "./adminSchema";

const route = useRoute();
const router = useRouter();
const rows = ref<Record<string, unknown>[]>([]);
const filterValues = ref<Record<string, string | number | boolean | null>>({});
const count = ref(0);
const loading = ref(false);
const error = ref("");

const resource = computed(() => String(route.params.resource ?? ""));
const model = computed(() => adminModels.find((item) => item.resource === resource.value));
const columns = computed(() => model.value?.fields.filter((field) => !field.writeOnly) ?? []);

function initFilters() {
  filterValues.value = Object.fromEntries(
    (model.value?.filters ?? []).map((filter) => [filter.name, filter.type === "boolean" ? null : ""]),
  );
}

async function loadRows() {
  if (!model.value) {
    rows.value = [];
    return;
  }

  loading.value = true;
  error.value = "";

  try {
    const response = await model.value.api.list({ limit: 100, ...cleanFilters() });
    rows.value = response.results;
    count.value = response.count;
  } catch (err) {
    error.value = err instanceof Error ? err.message : "Unable to load objects";
  } finally {
    loading.value = false;
  }
}

function filterInputType(filter: AdminFilter) {
  return filter.type === "integer" || filter.type === "real" ? "number" : "text";
}

function cleanFilters() {
  const params: Record<string, string | number | boolean | null> = {};

  for (const filter of model.value?.filters ?? []) {
    const value = filterValues.value[filter.name];
    if (value === "" || value === null || value === undefined) {
      continue;
    }

    if (filter.type === "integer" || filter.type === "real") {
      params[filter.name] = Number(value);
    } else {
      params[filter.name] = value;
    }
  }

  return params;
}

async function resetFilters() {
  initFilters();
  await loadRows();
}

async function removeRow(row: Record<string, unknown>) {
  if (!model.value || typeof row.id !== "number") {
    return;
  }

  if (!window.confirm(`Delete ${model.value.name} #${row.id}?`)) {
    return;
  }

  await model.value.api.remove(row.id);
  await loadRows();
}

function displayValue(value: unknown) {
  if (value === null || value === undefined) {
    return "-";
  }

  if (typeof value === "boolean") {
    return value ? "Yes" : "No";
  }

  if (typeof value === "object") {
    const objectValue = value as Record<string, unknown>;
    return objectValue.name ?? objectValue.title ?? objectValue.username ?? objectValue.email ?? objectValue.id ?? JSON.stringify(value);
  }

  return value;
}

watch(resource, async () => {
  initFilters();
  await loadRows();
}, { immediate: true });
</script>

<template>
  <section v-if="model" class="admin-panel">
    <div class="admin-toolbar">
      <div>
        <p>{{ model.resource }}</p>
        <h1>{{ model.name }}</h1>
      </div>
      <div class="admin-actions">
        <button type="button" @click="loadRows">Refresh</button>
        <RouterLink class="primary-link" :to="`/admin/${model.resource}/new`">Create</RouterLink>
      </div>
    </div>

    <form v-if="model.filters.length > 0" class="filter-card" @submit.prevent="loadRows">
      <div class="filter-heading">
        <h2>Filters</h2>
        <span>{{ model.filters.length }} available</span>
      </div>

      <div class="filter-grid">
        <label v-for="filter in model.filters" :key="filter.name">
          <span>{{ filter.label }}</span>
          <select v-if="filter.type === 'boolean'" v-model="filterValues[filter.name]">
            <option :value="null">Any</option>
            <option :value="true">Yes</option>
            <option :value="false">No</option>
          </select>
          <input
            v-else
            v-model="filterValues[filter.name]"
            :step="filter.type === 'real' ? 'any' : '1'"
            :type="filterInputType(filter)"
          />
        </label>
      </div>

      <div class="filter-actions">
        <button type="submit">Apply filters</button>
        <button type="button" @click="resetFilters">Reset</button>
      </div>
    </form>

    <p v-if="loading" class="state-message">Loading...</p>
    <p v-else-if="error" class="error-message">{{ error }}</p>

    <div v-else class="table-card">
      <div class="table-meta">{{ rows.length }} of {{ count }} objects</div>
      <div class="table-scroll">
        <table>
          <thead>
            <tr>
              <th v-for="field in columns" :key="field.name">{{ field.label }}</th>
              <th class="actions-column">Actions</th>
            </tr>
          </thead>
          <tbody>
            <tr v-if="rows.length === 0">
              <td :colspan="columns.length + 1">No objects yet.</td>
            </tr>
            <tr v-for="row in rows" :key="String(row.id)">
              <td v-for="field in columns" :key="field.name">
                {{ displayValue(row[field.name]) }}
              </td>
              <td class="row-actions">
                <button type="button" @click="router.push(`/admin/${model.resource}/${row.id}/edit`)">Edit</button>
                <button class="danger-button" type="button" @click="removeRow(row)">Delete</button>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </section>

  <p v-else class="error-message">Unknown admin model: {{ resource }}</p>
</template>

<style scoped>
.admin-panel {
  display: grid;
  gap: 24px;
}

.admin-toolbar {
  align-items: center;
  display: flex;
  gap: 16px;
  justify-content: space-between;
}

.admin-toolbar p,
.table-meta {
  color: #64708a;
  margin: 0;
}

.admin-toolbar h1 {
  font-size: 34px;
  margin: 4px 0 0;
}

.admin-actions,
.row-actions {
  display: flex;
  gap: 8px;
}

button,
.primary-link {
  border: 1px solid #cbd4e4;
  border-radius: 10px;
  background: #ffffff;
  color: #172033;
  cursor: pointer;
  font: inherit;
  padding: 9px 12px;
  text-decoration: none;
}

.filter-card {
  background: #ffffff;
  border: 1px solid #dde2ee;
  border-radius: 18px;
  box-shadow: 0 12px 36px rgba(23, 32, 51, 0.08);
  display: grid;
  gap: 16px;
  padding: 18px;
}

.filter-heading {
  align-items: end;
  display: flex;
  gap: 10px;
}

.filter-heading h2 {
  font-size: 20px;
  margin: 0;
}

.filter-heading span {
  color: #64708a;
  font-size: 13px;
  padding-bottom: 2px;
}

.filter-grid {
  display: grid;
  gap: 14px;
  grid-template-columns: repeat(auto-fit, minmax(180px, 1fr));
}

.filter-grid label {
  color: #344054;
  display: grid;
  gap: 7px;
  font-weight: 700;
}

.filter-grid input,
.filter-grid select {
  border: 1px solid #cbd4e4;
  border-radius: 10px;
  color: #172033;
  font: inherit;
  padding: 9px 12px;
}

.filter-actions {
  display: flex;
  gap: 8px;
}

.primary-link {
  background: #2446c6;
  border-color: #2446c6;
  color: #ffffff;
}

.danger-button {
  color: #b42318;
}

.table-card {
  background: #ffffff;
  border: 1px solid #dde2ee;
  border-radius: 18px;
  box-shadow: 0 12px 36px rgba(23, 32, 51, 0.08);
  display: grid;
  gap: 12px;
  padding: 18px;
}

.table-scroll {
  overflow-x: auto;
}

table {
  border-collapse: collapse;
  min-width: 720px;
  width: 100%;
}

th,
td {
  border-bottom: 1px solid #edf0f6;
  padding: 12px;
  text-align: left;
  vertical-align: top;
}

th {
  color: #64708a;
  font-size: 12px;
  letter-spacing: 0.06em;
  text-transform: uppercase;
}

.actions-column {
  width: 160px;
}

.state-message,
.error-message {
  background: #ffffff;
  border-radius: 14px;
  padding: 16px;
}

.error-message {
  color: #b42318;
}

@media (max-width: 760px) {
  .admin-toolbar {
    align-items: flex-start;
    flex-direction: column;
  }
}
</style>
"#
}

#[allow(dead_code)]
fn admin_model_form_vue() -> &'static str {
    r#"<script setup lang="ts">
import { computed, ref, watch } from "vue";
import { useRoute, useRouter } from "vue-router";
import { adminModels, type AdminField } from "./adminSchema";

const route = useRoute();
const router = useRouter();
const form = ref<Record<string, string | number | boolean | null>>({});
const loading = ref(false);
const saving = ref(false);
const error = ref("");

const resource = computed(() => String(route.params.resource ?? ""));
const id = computed(() => Number(route.params.id));
const isEdit = computed(() => Number.isFinite(id.value));
const model = computed(() => adminModels.find((item) => item.resource === resource.value));
const fields = computed(() => model.value?.fields.filter((field) => !field.readOnly) ?? []);

function emptyValue(field: AdminField) {
  return field.type === "boolean" ? false : "";
}

function inputType(field: AdminField) {
  return field.type === "integer" || field.type === "real" ? "number" : "text";
}

async function loadObject() {
  if (!model.value) {
    return;
  }

  form.value = Object.fromEntries(fields.value.map((field) => [field.name, emptyValue(field)]));

  if (!isEdit.value) {
    return;
  }

  loading.value = true;
  error.value = "";

  try {
    const object = await model.value.api.retrieve(id.value);
    const nextForm: Record<string, string | number | boolean | null> = {};
    for (const field of fields.value) {
      const directValue = object[field.name];
      const relationValue = field.relationField ? object[field.relationField] : undefined;
      const relationId = relationValue && typeof relationValue === "object"
        ? (relationValue as Record<string, unknown>).id
        : undefined;
      const value = directValue ?? relationId ?? emptyValue(field);
      nextForm[field.name] = value as string | number | boolean | null;
    }
    form.value = nextForm;
  } catch (err) {
    error.value = err instanceof Error ? err.message : "Unable to load object";
  } finally {
    loading.value = false;
  }
}

function normalizeValue(field: AdminField) {
  const value = form.value[field.name];

  if (field.type === "boolean") {
    return Boolean(value);
  }

  if (value === "") {
    if (field.nullable) {
      return null;
    }
    if (field.type === "text") {
      return "";
    }
    return undefined;
  }

  if (field.type === "integer" || field.type === "real") {
    return Number(value);
  }

  return value;
}

async function submit() {
  if (!model.value) {
    return;
  }

  saving.value = true;
  error.value = "";

  const payload: Record<string, unknown> = {};
  for (const field of fields.value) {
    const value = normalizeValue(field);
    if (value !== undefined) {
      payload[field.name] = value;
    }
  }

  try {
    if (isEdit.value) {
      await model.value.api.update(id.value, payload);
    } else {
      await model.value.api.create(payload);
    }
    router.push(`/admin/${model.value.resource}`);
  } catch (err) {
    error.value = err instanceof Error ? err.message : "Unable to save object";
  } finally {
    saving.value = false;
  }
}

watch(() => [resource.value, route.params.id], loadObject, { immediate: true });
</script>

<template>
  <section v-if="model" class="admin-panel">
    <div class="admin-toolbar">
      <div>
        <p>{{ model.resource }}</p>
        <h1>{{ isEdit ? `Edit ${model.name}` : `Create ${model.name}` }}</h1>
      </div>
      <RouterLink class="secondary-link" :to="`/admin/${model.resource}`">Back to list</RouterLink>
    </div>

    <p v-if="loading" class="state-message">Loading...</p>

    <form v-else class="admin-form" @submit.prevent="submit">
      <label v-for="field in fields" :key="field.name" :class="{ checkbox: field.type === 'boolean' }">
        <span>{{ field.label }}</span>
        <input
          v-if="field.type === 'boolean'"
          v-model="form[field.name]"
          type="checkbox"
        />
        <input
          v-else
          v-model="form[field.name]"
          :min="field.type === 'integer' || field.type === 'real' ? undefined : undefined"
          :required="field.required && !field.hasDefault && !field.nullable"
          :step="field.type === 'real' ? 'any' : '1'"
          :type="inputType(field)"
        />
        <small v-if="field.relatedModel">{{ field.relatedModel }} id</small>
      </label>

      <p v-if="error" class="error-message">{{ error }}</p>

      <div class="form-actions">
        <button class="primary-button" :disabled="saving" type="submit">
          {{ saving ? "Saving..." : "Save" }}
        </button>
        <RouterLink class="secondary-link" :to="`/admin/${model.resource}`">Cancel</RouterLink>
      </div>
    </form>
  </section>

  <p v-else class="error-message">Unknown admin model: {{ resource }}</p>
</template>

<style scoped>
.admin-panel {
  display: grid;
  gap: 24px;
}

.admin-toolbar {
  align-items: center;
  display: flex;
  gap: 16px;
  justify-content: space-between;
}

.admin-toolbar p {
  color: #64708a;
  margin: 0;
}

.admin-toolbar h1 {
  font-size: 34px;
  margin: 4px 0 0;
}

.admin-form {
  background: #ffffff;
  border: 1px solid #dde2ee;
  border-radius: 18px;
  box-shadow: 0 12px 36px rgba(23, 32, 51, 0.08);
  display: grid;
  gap: 18px;
  max-width: 680px;
  padding: 22px;
}

label {
  color: #344054;
  display: grid;
  gap: 7px;
  font-weight: 700;
}

label.checkbox {
  align-items: center;
  display: flex;
}

input {
  border: 1px solid #cbd4e4;
  border-radius: 10px;
  color: #172033;
  font: inherit;
  padding: 10px 12px;
}

input[type="checkbox"] {
  height: 18px;
  width: 18px;
}

small {
  color: #64708a;
  font-weight: 400;
}

.form-actions {
  align-items: center;
  display: flex;
  gap: 10px;
}

.primary-button,
.secondary-link {
  border: 1px solid #2446c6;
  border-radius: 10px;
  cursor: pointer;
  font: inherit;
  padding: 10px 14px;
  text-decoration: none;
}

.primary-button {
  background: #2446c6;
  color: #ffffff;
}

.secondary-link {
  background: #ffffff;
  color: #2446c6;
}

.state-message,
.error-message {
  background: #ffffff;
  border-radius: 14px;
  padding: 16px;
}

.error-message {
  color: #b42318;
}

@media (max-width: 760px) {
  .admin-toolbar {
    align-items: flex-start;
    flex-direction: column;
  }
}
</style>
"#
}

#[allow(dead_code)]
fn legacy_admin_routes_ts() -> &'static str {
    r#"import type { RouteRecordRaw } from "vue-router";
import AdminModelForm from "./AdminModelForm.vue";
import AdminModelList from "./AdminModelList.vue";
import AdminModelTable from "./AdminModelTable.vue";

export const adminRoutes: RouteRecordRaw[] = [
  { path: "", component: AdminModelList },
  { path: ":resource", component: AdminModelTable },
  { path: ":resource/new", component: AdminModelForm },
  { path: ":resource/:id/edit", component: AdminModelForm },
];
"#
}

fn admin_field_type(ty: FieldType) -> &'static str {
    match ty {
        FieldType::Integer => "integer",
        FieldType::Text => "text",
        FieldType::Boolean => "boolean",
        FieldType::Real => "real",
        FieldType::DateTime => "datetime",
        FieldType::Json => "json",
        FieldType::Choice => "text",
    }
}

fn human_label(value: &str) -> String {
    let mut label = String::new();
    for part in value.split('_').filter(|part| !part.is_empty()) {
        if !label.is_empty() {
            label.push(' ');
        }
        let mut chars = part.chars();
        match chars.next() {
            Some(first) => {
                label.push(first.to_ascii_uppercase());
                label.push_str(chars.as_str());
            }
            None => {}
        }
    }
    if label.is_empty() {
        value.to_string()
    } else {
        label
    }
}

fn js_string(value: &str) -> String {
    serde_json::to_string(value).expect("serializing string cannot fail")
}

async fn apply_app_migrations(
    db: &SqliteBackend,
    apps_dir: &std::path::Path,
    app: &str,
) -> ManageResult<()> {
    let migrations_dir = migrations_dir(apps_dir, app);
    for name in db
        .apply_migrations_dir_with_namespace(app, &migrations_dir)
        .await?
    {
        println!("Applied {app}: {name}");
    }
    Ok(())
}

fn migrations_dir(apps_dir: &std::path::Path, app: &str) -> PathBuf {
    let project_dir = app_migrations_dir(apps_dir, app);
    if project_dir.exists() || app != "auth" {
        return project_dir;
    }

    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("src/auth/migrations")
}

#[derive(Debug, Clone)]
struct GeneratedModel {
    rust_name: String,
    snake_name: String,
    table_name: String,
    const_name: String,
    serializer_name: String,
    filterset_name: String,
    viewset_name: String,
}

fn startapp(name: &str, apps_dir: PathBuf, models: Vec<String>) -> ManageResult<()> {
    validate_app_name(name)?;
    let models = generated_models(name, models)?;

    let app_dir = apps_dir.join(name);
    if app_dir.exists() {
        return Err(format!("app already exists: {}", app_dir.display()).into());
    }

    fs::create_dir_all(&app_dir)?;
    fs::write(app_dir.join("mod.rs"), mod_template(name, &models))?;
    fs::write(app_dir.join("models.rs"), models_template(&models))?;
    fs::write(
        app_dir.join("serializers.rs"),
        serializers_template(&models),
    )?;
    fs::write(app_dir.join("filters.rs"), filters_template(&models))?;
    fs::write(app_dir.join("views.rs"), views_template(&models))?;

    update_apps_mod(&apps_dir, name)?;

    println!("created app {}", app_dir.display());
    println!(
        "created models: {}",
        models
            .iter()
            .map(|model| model.rust_name.as_str())
            .collect::<Vec<_>>()
            .join(", ")
    );
    println!("add it to apps::installed_apps(): .add({name}::module())");

    Ok(())
}

fn generated_models(app: &str, models: Vec<String>) -> ManageResult<Vec<GeneratedModel>> {
    let models = if models.is_empty() {
        vec![default_model_name(app)]
    } else {
        models
    };

    let mut generated = Vec::new();
    for model in models {
        validate_model_name(&model)?;
        let snake_name = pascal_to_snake(&model);
        if generated
            .iter()
            .any(|existing: &GeneratedModel| existing.snake_name == snake_name)
        {
            return Err(format!("duplicate model name after normalization: {model}").into());
        }

        generated.push(GeneratedModel {
            rust_name: model.clone(),
            snake_name: snake_name.clone(),
            table_name: format!("{app}_{snake_name}"),
            const_name: snake_name.to_ascii_uppercase(),
            serializer_name: format!("{model}Serializer"),
            filterset_name: format!("{model}FilterSet"),
            viewset_name: format!("{model}ViewSet"),
        });
    }

    Ok(generated)
}

fn default_model_name(app: &str) -> String {
    let base = app
        .strip_suffix("app")
        .filter(|base| !base.is_empty())
        .unwrap_or(app);
    camel_case(base)
}

fn update_apps_mod(apps_dir: &std::path::Path, name: &str) -> ManageResult<()> {
    fs::create_dir_all(apps_dir)?;
    let mod_path = apps_dir.join("mod.rs");
    let line = format!("pub mod {name};");
    let mut content = fs::read_to_string(&mod_path).unwrap_or_default();

    if !content.lines().any(|existing| existing.trim() == line) {
        if !content.is_empty() && !content.ends_with('\n') {
            content.push('\n');
        }
        content.push_str(&line);
        content.push('\n');
        fs::write(mod_path, content)?;
    }

    Ok(())
}

fn app_migrations_dir(apps_dir: &std::path::Path, app: &str) -> PathBuf {
    apps_dir.join(app).join("migrations")
}

fn migration_files(migrations_dir: &std::path::Path) -> ManageResult<Vec<PathBuf>> {
    if !migrations_dir.exists() {
        return Ok(Vec::new());
    }

    let mut files = Vec::new();
    for entry in fs::read_dir(migrations_dir)? {
        let path = entry?.path();
        if path.extension().is_some_and(|extension| extension == "sql") {
            files.push(path);
        }
    }
    Ok(files)
}

fn next_migration_number(migrations_dir: &std::path::Path) -> ManageResult<u32> {
    let max = migration_files(migrations_dir)?
        .iter()
        .filter_map(|path| path.file_name()?.to_str()?.get(0..4)?.parse::<u32>().ok())
        .max()
        .unwrap_or(0);
    Ok(max + 1)
}

fn slugify(value: &str) -> String {
    let mut slug = String::new();
    for ch in value.chars() {
        if ch.is_ascii_alphanumeric() {
            slug.push(ch.to_ascii_lowercase());
        } else if !slug.ends_with('_') {
            slug.push('_');
        }
    }
    let slug = slug.trim_matches('_').to_string();
    if slug.is_empty() {
        "auto".to_string()
    } else {
        slug
    }
}

fn validate_app_name(name: &str) -> ManageResult<()> {
    let mut chars = name.chars();
    let Some(first) = chars.next() else {
        return Err("app name cannot be empty".into());
    };
    if !first.is_ascii_lowercase() {
        return Err("app name must start with a lowercase ascii letter".into());
    }
    if !chars.all(|ch| ch.is_ascii_lowercase() || ch.is_ascii_digit() || ch == '_') {
        return Err(
            "app name must contain only lowercase ascii letters, digits, and underscores".into(),
        );
    }
    Ok(())
}

fn validate_model_name(name: &str) -> ManageResult<()> {
    let mut chars = name.chars();
    let Some(first) = chars.next() else {
        return Err("model name cannot be empty".into());
    };
    if !first.is_ascii_uppercase() {
        return Err("model name must start with an uppercase ascii letter".into());
    }
    if !chars.all(|ch| ch.is_ascii_alphanumeric() || ch == '_') {
        return Err("model name must contain only ascii letters, digits, and underscores".into());
    }
    Ok(())
}

fn mod_template(name: &str, models: &[GeneratedModel]) -> String {
    let module_type = format!("{}Module", camel_case(name));
    let mut registrations = String::new();
    for model in models {
        registrations.push_str(&format!(
            r#"        ctx.viewset_with("/{snake_name}", views::{viewset_name});
"#,
            snake_name = model.snake_name,
            viewset_name = model.viewset_name,
        ));
    }

    format!(
        r#"pub mod filters;
pub mod models;
pub mod serializers;
pub mod views;

use che_rest::{{AppModule, ModuleContext}};

pub fn module() -> {module_type} {{
    {module_type}
}}

pub struct {module_type};

impl AppModule for {module_type} {{
    fn name(&self) -> &'static str {{
        "{name}"
    }}

    fn init(&self, ctx: &mut ModuleContext) {{
{registrations}    }}
}}
"#
    )
}

fn models_template(models: &[GeneratedModel]) -> String {
    let mut out = String::from("use che_orm::{Model, NaiveDateTime};\n\n");
    for model in models {
        out.push_str(&format!(
            r#"#[derive(Debug, Clone, Model)]
#[model(table = "{table_name}")]
pub struct {rust_name} {{
    #[field(primary_key)]
    pub id: i64,

    pub name: String,

    #[field(auto_now_add)]
    pub created_at: NaiveDateTime,

    #[field(auto_now)]
    pub updated_at: NaiveDateTime,
}}

"#,
            table_name = model.table_name,
            rust_name = model.rust_name,
        ));
    }
    out
}

fn serializers_template(models: &[GeneratedModel]) -> String {
    let mut out = String::from("use che_rest::{Field, Serializer};\n\nuse super::models::{");
    out.push_str(
        &models
            .iter()
            .map(|model| model.rust_name.as_str())
            .collect::<Vec<_>>()
            .join(", "),
    );
    out.push_str("};\n\n");

    for model in models {
        out.push_str(&format!(
            r#"static {const_name}_FIELDS: &[Field] = &[
    Field::new("id").read_only(),
    Field::new("name"),
    Field::new("created_at").read_only(),
    Field::new("updated_at").read_only(),
];

#[derive(Clone, Copy, Default)]
pub struct {serializer_name};

impl Serializer for {serializer_name} {{
    type Model = {rust_name};

    fn fields(&self) -> &'static [Field] {{
        {const_name}_FIELDS
    }}
}}

"#,
            const_name = model.const_name,
            serializer_name = model.serializer_name,
            rust_name = model.rust_name,
        ));
    }
    out
}

fn filters_template(models: &[GeneratedModel]) -> String {
    let mut out = String::from("use che_rest::{Filter, FilterSetSpec};\n\nuse super::models::{");
    out.push_str(
        &models
            .iter()
            .map(|model| format!("{}, {}Fields", model.rust_name, model.rust_name))
            .collect::<Vec<_>>()
            .join(", "),
    );
    out.push_str("};\n\n");

    for model in models {
        out.push_str(&format!(
            r#"static {const_name}_FILTERS: &[Filter<{rust_name}>] = &[
    Filter::exact({rust_name}Fields::NAME),
    Filter::contains({rust_name}Fields::NAME),
    Filter::gte({rust_name}Fields::CREATED_AT),
    Filter::lte({rust_name}Fields::CREATED_AT),
    Filter::gte({rust_name}Fields::UPDATED_AT),
    Filter::lte({rust_name}Fields::UPDATED_AT),
];

#[derive(Clone, Copy, Default)]
pub struct {filterset_name};

impl FilterSetSpec for {filterset_name} {{
    type Model = {rust_name};

    fn filters(&self) -> &'static [Filter<{rust_name}>] {{
        {const_name}_FILTERS
    }}
}}

"#,
            const_name = model.const_name,
            filterset_name = model.filterset_name,
            rust_name = model.rust_name,
        ));
    }
    out
}

fn views_template(models: &[GeneratedModel]) -> String {
    let mut out =
        String::from("use che_rest::{AllowAny, ViewSet};\n\nuse super::{\n    filters::{");
    out.push_str(
        &models
            .iter()
            .map(|model| model.filterset_name.as_str())
            .collect::<Vec<_>>()
            .join(", "),
    );
    out.push_str("},\n    models::{");
    out.push_str(
        &models
            .iter()
            .map(|model| model.rust_name.as_str())
            .collect::<Vec<_>>()
            .join(", "),
    );
    out.push_str("},\n    serializers::{");
    out.push_str(
        &models
            .iter()
            .map(|model| model.serializer_name.as_str())
            .collect::<Vec<_>>()
            .join(", "),
    );
    out.push_str("},\n};\n\n");

    for model in models {
        out.push_str(&format!(
            "#[derive(Clone, Copy, Default)]\npub struct {viewset_name};\n\n#[che_rest::async_trait]\nimpl ViewSet for {viewset_name} {{\n    type Model = {rust_name};\n    type Serializer = {serializer_name};\n    type FilterSet = {filterset_name};\n    type Permission = AllowAny;\n}}\n\n",
            viewset_name = model.viewset_name,
            rust_name = model.rust_name,
            serializer_name = model.serializer_name,
            filterset_name = model.filterset_name,
        ));
    }
    out
}

fn pascal_to_snake(name: &str) -> String {
    let mut out = String::new();
    for (index, ch) in name.chars().enumerate() {
        if ch == '_' {
            if !out.ends_with('_') {
                out.push('_');
            }
        } else if ch.is_ascii_uppercase() {
            if index > 0 && !out.ends_with('_') {
                out.push('_');
            }
            out.push(ch.to_ascii_lowercase());
        } else {
            out.push(ch);
        }
    }
    out.trim_matches('_').to_string()
}

fn camel_case(name: &str) -> String {
    name.split('_')
        .filter(|part| !part.is_empty())
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                Some(first) => first.to_ascii_uppercase().to_string() + chars.as_str(),
                None => String::new(),
            }
        })
        .collect()
}
