// Frozen auth:0001_initial. Change auth models through a new migration;
// never regenerate this snapshot from the runtime model schema.
use che_orm::{
    ColumnState, ColumnType, ForeignKeyState, Migration, MigrationId, MigrationOperation, ModelKey,
    ModelState, TableState,
};

pub fn migration() -> Migration {
    Migration::new(
        MigrationId {
            app: "auth".into(),
            name: "0001_initial".into(),
        },
        vec![],
        vec![
            MigrationOperation::CreateModel {
                model: ModelState {
                    key: ModelKey {
                        app: "auth".into(),
                        name: "User".into(),
                    },
                    table: TableState {
                        name: "auth_users".into(),
                        columns: vec![
                            ColumnState {
                                field_name: "id".into(),
                                name: "id".into(),
                                column_type: ColumnType::Integer,
                                nullable: false,
                                primary_key: true,
                                unique: false,
                                default: None,
                                check: None,
                                choices: None,
                                references: None,
                                auto_now_add: false,
                                auto_now: false,
                            },
                            ColumnState {
                                field_name: "username".into(),
                                name: "username".into(),
                                column_type: ColumnType::Text,
                                nullable: false,
                                primary_key: false,
                                unique: true,
                                default: None,
                                check: None,
                                choices: None,
                                references: None,
                                auto_now_add: false,
                                auto_now: false,
                            },
                            ColumnState {
                                field_name: "password_hash".into(),
                                name: "password_hash".into(),
                                column_type: ColumnType::Text,
                                nullable: false,
                                primary_key: false,
                                unique: false,
                                default: None,
                                check: None,
                                choices: None,
                                references: None,
                                auto_now_add: false,
                                auto_now: false,
                            },
                            ColumnState {
                                field_name: "is_active".into(),
                                name: "is_active".into(),
                                column_type: ColumnType::Boolean,
                                nullable: false,
                                primary_key: false,
                                unique: false,
                                default: Some("true".into()),
                                check: None,
                                choices: None,
                                references: None,
                                auto_now_add: false,
                                auto_now: false,
                            },
                            ColumnState {
                                field_name: "is_staff".into(),
                                name: "is_staff".into(),
                                column_type: ColumnType::Boolean,
                                nullable: false,
                                primary_key: false,
                                unique: false,
                                default: Some("false".into()),
                                check: None,
                                choices: None,
                                references: None,
                                auto_now_add: false,
                                auto_now: false,
                            },
                            ColumnState {
                                field_name: "is_admin".into(),
                                name: "is_admin".into(),
                                column_type: ColumnType::Boolean,
                                nullable: false,
                                primary_key: false,
                                unique: false,
                                default: Some("false".into()),
                                check: None,
                                choices: None,
                                references: None,
                                auto_now_add: false,
                                auto_now: false,
                            },
                            ColumnState {
                                field_name: "is_superuser".into(),
                                name: "is_superuser".into(),
                                column_type: ColumnType::Boolean,
                                nullable: false,
                                primary_key: false,
                                unique: false,
                                default: Some("false".into()),
                                check: None,
                                choices: None,
                                references: None,
                                auto_now_add: false,
                                auto_now: false,
                            },
                        ],
                        unique_constraints: vec![],
                        indexes: vec![],
                    },
                },
            },
            MigrationOperation::CreateModel {
                model: ModelState {
                    key: ModelKey {
                        app: "auth".into(),
                        name: "AuthToken".into(),
                    },
                    table: TableState {
                        name: "auth_tokens".into(),
                        columns: vec![
                            ColumnState {
                                field_name: "id".into(),
                                name: "id".into(),
                                column_type: ColumnType::Integer,
                                nullable: false,
                                primary_key: true,
                                unique: false,
                                default: None,
                                check: None,
                                choices: None,
                                references: None,
                                auto_now_add: false,
                                auto_now: false,
                            },
                            ColumnState {
                                field_name: "user_id".into(),
                                name: "user_id".into(),
                                column_type: ColumnType::Integer,
                                nullable: false,
                                primary_key: false,
                                unique: false,
                                default: None,
                                check: None,
                                choices: None,
                                references: Some(ForeignKeyState {
                                    target: "auth_users(id)".into(),
                                    on_delete: Some("cascade".into()),
                                }),
                                auto_now_add: false,
                                auto_now: false,
                            },
                            ColumnState {
                                field_name: "key_hash".into(),
                                name: "key_hash".into(),
                                column_type: ColumnType::Text,
                                nullable: false,
                                primary_key: false,
                                unique: true,
                                default: None,
                                check: None,
                                choices: None,
                                references: None,
                                auto_now_add: false,
                                auto_now: false,
                            },
                        ],
                        unique_constraints: vec![],
                        indexes: vec![vec!["user_id".into()]],
                    },
                },
            },
            MigrationOperation::CreateModel {
                model: ModelState {
                    key: ModelKey {
                        app: "auth".into(),
                        name: "AuthSession".into(),
                    },
                    table: TableState {
                        name: "auth_sessions".into(),
                        columns: vec![
                            ColumnState {
                                field_name: "id".into(),
                                name: "id".into(),
                                column_type: ColumnType::Integer,
                                nullable: false,
                                primary_key: true,
                                unique: false,
                                default: None,
                                check: None,
                                choices: None,
                                references: None,
                                auto_now_add: false,
                                auto_now: false,
                            },
                            ColumnState {
                                field_name: "user_id".into(),
                                name: "user_id".into(),
                                column_type: ColumnType::Integer,
                                nullable: false,
                                primary_key: false,
                                unique: false,
                                default: None,
                                check: None,
                                choices: None,
                                references: Some(ForeignKeyState {
                                    target: "auth_users(id)".into(),
                                    on_delete: Some("cascade".into()),
                                }),
                                auto_now_add: false,
                                auto_now: false,
                            },
                            ColumnState {
                                field_name: "key_hash".into(),
                                name: "key_hash".into(),
                                column_type: ColumnType::Text,
                                nullable: false,
                                primary_key: false,
                                unique: true,
                                default: None,
                                check: None,
                                choices: None,
                                references: None,
                                auto_now_add: false,
                                auto_now: false,
                            },
                            ColumnState {
                                field_name: "csrf_hash".into(),
                                name: "csrf_hash".into(),
                                column_type: ColumnType::Text,
                                nullable: false,
                                primary_key: false,
                                unique: false,
                                default: None,
                                check: None,
                                choices: None,
                                references: None,
                                auto_now_add: false,
                                auto_now: false,
                            },
                            ColumnState {
                                field_name: "data".into(),
                                name: "data".into(),
                                column_type: ColumnType::Text,
                                nullable: false,
                                primary_key: false,
                                unique: false,
                                default: None,
                                check: None,
                                choices: None,
                                references: None,
                                auto_now_add: false,
                                auto_now: false,
                            },
                            ColumnState {
                                field_name: "revision".into(),
                                name: "revision".into(),
                                column_type: ColumnType::Integer,
                                nullable: false,
                                primary_key: false,
                                unique: false,
                                default: None,
                                check: None,
                                choices: None,
                                references: None,
                                auto_now_add: false,
                                auto_now: false,
                            },
                            ColumnState {
                                field_name: "expires_at".into(),
                                name: "expires_at".into(),
                                column_type: ColumnType::DateTime,
                                nullable: false,
                                primary_key: false,
                                unique: false,
                                default: None,
                                check: None,
                                choices: None,
                                references: None,
                                auto_now_add: false,
                                auto_now: false,
                            },
                            ColumnState {
                                field_name: "created_at".into(),
                                name: "created_at".into(),
                                column_type: ColumnType::DateTime,
                                nullable: false,
                                primary_key: false,
                                unique: false,
                                default: None,
                                check: None,
                                choices: None,
                                references: None,
                                auto_now_add: true,
                                auto_now: false,
                            },
                        ],
                        unique_constraints: vec![],
                        indexes: vec![vec!["user_id".into()]],
                    },
                },
            },
        ],
    )
}
